/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#3a3939",
        "surface-container-high": "#2a2a2a",
        "primary-container": "#ff6b00",
        background: "#131313",
        "outline-variant": "#5a4136",
        "on-tertiary-fixed": "#171c20",
        "surface-dim": "#131313",
        "on-secondary": "#002e6a",
        "error-container": "#93000a",
        "primary-fixed": "#ffdbcc",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#c3c7cd",
        "inverse-primary": "#a04100",
        "on-secondary-fixed": "#001a42",
        "on-primary-fixed": "#351000",
        primary: "#ffb693",
        "surface-tint": "#ffb693",
        "surface-container-highest": "#353534",
        "secondary-fixed-dim": "#adc6ff",
        "on-tertiary-container": "#2d3136",
        "surface-container-lowest": "#0e0e0e",
        tertiary: "#c3c7cd",
        "on-surface": "#e5e2e1",
        "secondary-container": "#0566d9",
        "inverse-on-surface": "#313030",
        "on-surface-variant": "#e2bfb0",
        "on-secondary-fixed-variant": "#004395",
        "on-secondary-container": "#e6ecff",
        "on-primary": "#561f00",
        "primary-fixed-dim": "#ffb693",
        secondary: "#adc6ff",
        "inverse-surface": "#e5e2e1",
        error: "#ffb4ab",
        "surface-container": "#201f1f",
        "on-primary-fixed-variant": "#7a3000",
        "on-tertiary": "#2c3136",
        surface: "#131313",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#572000",
        outline: "#a98a7d",
        "tertiary-fixed": "#dfe3e9",
        "on-tertiary-fixed-variant": "#43474c",
        "surface-container-low": "#1c1b1b",
        "on-background": "#e5e2e1",
        "tertiary-container": "#95999f",
        "surface-variant": "#353534",
        "secondary-fixed": "#d8e2ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        xs: "4px",
        md: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        xl: "40px",
        sm: "8px",
        lg: "24px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Geist"],
        "headline-md": ["Geist"],
        "headline-lg": ["Geist"],
        "label-caps": ["JetBrains Mono"],
        "data-mono": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "display-lg": ["Geist"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "1.0", letterSpacing: "0.08em", fontWeight: "700" }],
        "data-mono": ["13px", { lineHeight: "1.0", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-lg": ["56px", { lineHeight: "1.05", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};